version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: fake-payment.nginx
    volumes:
      - ../public:/var/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - fake-payment
  php:
    build:
      ./php
    container_name: fake-payment.php
    volumes:
      - ../.:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=10.5.0.1 remote_enable=1 remote_autostart=off  remote_port=9000"
    networks:
      - fake-payment
networks:
  fake-payment:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
